'use client';
import {useEffect,useState} from 'react';

const STAGES=['All','Search','Select','Login','Book','Payment','Confirm'];
const RANGES=[['15m','15 min'],['1h','1 hour'],['6h','6 hours'],['24h','24 hours']];
const ms=v=>Number(v||0)>=1000?`${(Number(v||0)/1000).toFixed(2)} s`:`${Math.round(Number(v||0))} ms`;
const pct=v=>`${Number(v||0).toFixed(1)}%`;
const delta=v=>v===null||v===undefined?'No baseline':`${v>=0?'↑':'↓'} ${Math.abs(Number(v)).toFixed(1)}%`;
const shortService=v=>String(v||'unknown').replace(/^easytravel-/,'').replaceAll('-',' ');
const when=v=>v?new Date(v).toLocaleString([], {month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const coeff=v=>v===null||v===undefined?'n/a':Number(v).toFixed(2);

function Badge({children,t='neutral'}){return <span className={`badge ${t}`}>{children}</span>}
function statusTone(v){return v==='CRITICAL'||v==='DEGRADED'?'bad':v==='WATCH'?'watch':'good'}
function infraTone(v){return v==='HIGH'?'bad':v==='MEDIUM'?'watch':'good'}

function Header({data,range,setRange,stage,setStage,onRefresh,loading}){
 const f=data?.filters;
 return <>
  <header className="topbar"><div className="brand"><div className="mark">M</div><div><b>SPARE-M</b><span>Business Reliability Intelligence</span></div></div><div className="topRight"><div className="live"><i/> {data?.agent_id||'waiting for telemetry'}</div><span>Updated {when(data?.updated_at)}</span></div></header>
  <div className="filterBar">
   <div className="filter"><label>Business journey</label><select value="Booking" disabled><option>Booking</option></select></div>
   <div className="filter"><label>Stage focus</label><select value={stage} onChange={e=>setStage(e.target.value)}>{STAGES.map(v=><option key={v}>{v}</option>)}</select></div>
   <div className="filter"><label>Time window</label><select value={range} onChange={e=>setRange(e.target.value)}>{RANGES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
   <div className="window"><span>Current</span><b>{when(f?.from)} → {when(f?.to)}</b><span>Baseline</span><b>{when(f?.baseline_from)} → {when(f?.baseline_to)}</b></div>
   <button className="refresh" onClick={onRefresh} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button>
  </div>
 </>
}

function ExecutiveView({data}){
 const x=data?.executive;if(!x)return <section className="executiveShell"><div className="emptyMsg">Waiting for enough telemetry to build the executive assessment.</div></section>;
 const b=x.business||{},t=x.technical||{},i=x.infrastructure||{};
 return <section className="executiveShell">
  <div className="execHeadline"><div><span className="eyebrow">CEO VIEW • CURRENT BUSINESS RELIABILITY</span><div className="headlineRow"><h1>{x.headline}</h1><Badge t={statusTone(x.status)}>{x.status}</Badge></div><p>{x.summary}</p></div><div className="confidence"><span>Evidence confidence</span><b>{x.confidence}%</b><small>{data?.focused_journey?.mode==='business-semantic'?'Business semantic mapping':'AI-assisted inferred mapping'}</small></div></div>
  <div className="valueGrid">
   <article className="valueCard business"><div className="valueHead"><span>BUSINESS VALUE</span><Badge t={statusTone(x.status)}>{b.stage}</Badge></div><div className="bigMetric"><b>{ms(b.p95_ms)}</b><span>Journey-stage p95</span><em className={(b.p95_delta_pct||0)>25?'down':''}>{delta(b.p95_delta_pct)} vs prior window</em></div><div className="miniGrid"><div><span>Error rate</span><b>{pct(b.error_rate)}</b></div><div><span>Selected traces</span><b>{b.selected_traces||0}</b></div><div><span>Journey confidence</span><b>{b.journey_structure_confidence??'—'}%</b><small>Txn link {b.transaction_linkage_confidence??'—'}%</small></div></div><div className="availability"><span>Conversion</span><b>Needs transaction identity</b><span>Revenue risk</span><b>Needs business value</b></div></article>
   <article className="valueCard technical"><div className="valueHead"><span>TECHNICAL VALUE</span><Badge t={t.operation?'watch':'neutral'}>{t.service?shortService(t.service):'No contributor'}</Badge></div><div className="causeBlock"><span>Strongest intelligence-ranked contributor</span><b>{t.operation||'No operation isolated'}</b><small>{t.service||'Waiting for technical evidence'}</small></div><div className="miniGrid"><div><span>Operation p95</span><b>{ms(t.p95_ms)}</b></div><div><span>Vs baseline</span><b>{delta(t.p95_delta_pct)}</b></div><div><span>Exclusive share</span><b>{t.exclusive_execution_share_pct==null?'—':pct(t.exclusive_execution_share_pct)}</b></div></div></article>
   <article className="valueCard infrastructure"><div className="valueHead"><span>INFRASTRUCTURE VALUE</span><Badge t={infraTone(i.contribution)}>{i.contribution} contribution</Badge></div><div className="bigMetric"><b>{i.hostname||'No host'}</b><span>Infrastructure contribution likelihood</span><em>{i.contribution==='LOW'?'Not the strongest current contributor':i.contribution==='MEDIUM'?'Possible contributor':'Credible contributor'}</em></div><div className="miniGrid"><div><span>CPU</span><b>{pct(i.cpu)}</b><small>{delta(i.cpu_delta_pct)}</small></div><div><span>Memory</span><b>{pct(i.memory)}</b><small>{delta(i.memory_delta_pct)}</small></div><div><span>Latency↔CPU</span><b>{coeff(i.latency_cpu)}</b></div></div></article>
  </div>
  <div className="decisionPath"><div className="pathTitle"><span>ONE-BLINK CAUSE PATH</span><b>Business → technical → infrastructure</b></div><div className="pathFlow">{(x.path||[]).map((p,idx)=><div key={`${p.type}-${idx}`} className={`pathNode ${p.type}`}><span>{p.type}</span><b>{p.type==='service'?shortService(p.label):p.label}</b>{idx<x.path.length-1&&<i>→</i>}</div>)}</div></div>
  <div className="execFooter"><div><span>Decision</span><b>{x.status==='HEALTHY'?'No immediate action required':'Investigate the intelligence-ranked contributor before scaling infrastructure.'}</b></div><div><span>Known evidence gaps</span><b>{(x.data_gaps||[]).join(' • ')}</b></div></div>
 </section>
}

function IntelligencePanel({data,onInvestigate,investigating,investigation}){
 const intel=data?.intelligence;if(!intel)return null;
 const j=intel.journey||{},e=intel.evidence||{},lead=e.leading_hypothesis,trace=intel.traces?.[0],dom=trace?.dominant_contributor,anomaly=intel.baselines?.operations?.[0],caps=intel.capabilities||{};
 const agent=investigation?.response;
 return <section className="intelligencePanel">
  <div className="intelligenceHead"><div><span className="eyebrow">SPARE-M INTELLIGENCE FABRIC</span><h2>Evidence before explanation</h2><p>Semantic understanding, process-mining signals, trace attribution, baselines and hypothesis verification are computed before any AI narrative.</p></div><div className="intActions"><Badge t={caps.agentic_investigation?'good':'watch'}>{caps.agentic_investigation?'Agentic investigator ready':'Deterministic intelligence active'}</Badge><button onClick={onInvestigate} disabled={investigating||!data?.agent_id}>{investigating?'Investigating…':'Run autonomous investigation'}</button></div></div>
  <div className="intelGrid">
   <article><span>Journey intelligence</span><b>Booking</b><strong>{j.structure_confidence||0}% structure confidence</strong><small>{j.transaction_linkage_confidence||0}% transaction linkage • {j.traces_with_business_semantics||0} semantic traces</small><p>{j.explanation}</p></article>
   <article><span>Trace intelligence</span><b>{dom?.operation||'No dominant operation'}</b><strong>{dom?pct(dom.execution_share_pct):'—'} exclusive execution share</strong><small>{dom?`${shortService(dom.service)} • ${ms(dom.self_time_ms)} self time`:'Waiting for trace tree evidence'}</small><p>{trace?`${trace.service_count} services • ${trace.span_count} spans • tree coverage ${pct(trace.evidence_quality?.tree_coverage_pct)}`:'No trace intelligence available.'}</p></article>
   <article><span>Baseline intelligence</span><b>{anomaly?.operation||'No operation anomaly'}</b><strong>{anomaly?`Anomaly score ${anomaly.anomaly_score}/100`:'—'}</strong><small>{anomaly?.baseline?`p95 ${ms(anomaly.current.p95_ms)} vs ${ms(anomaly.baseline.p95_ms)} (${delta(anomaly.delta.p95_pct)})`:'No prior-window baseline'}</small><p>{intel.baselines?.note}</p></article>
   <article className="hypothesis"><span>Leading hypothesis</span><b>{lead?.title||'Insufficient evidence'}</b><strong>{lead?`${lead.confidence}% hypothesis confidence`:'—'}</strong><small>{lead?.target||e.assessment}</small><p>{lead?.next_step||'Collect more evidence before concluding.'}</p></article>
  </div>
  {lead&&<div className="evidenceMatrix"><div><h3>Evidence supporting</h3>{(lead.evidence_for||[]).length?(lead.evidence_for||[]).map((x,i)=><p key={i}>+ {x}</p>):<p>No strong supporting signal yet.</p>}</div><div><h3>Evidence challenging</h3>{(lead.evidence_against||[]).length?(lead.evidence_against||[]).map((x,i)=><p key={i}>− {x}</p>):<p>No contradicting evidence identified.</p>}</div></div>}
  <div className="capabilityRow">{Object.entries(caps).map(([k,v])=><span key={k} className={v?'on':'off'}>{v?'●':'○'} {k.replaceAll('_',' ')}</span>)}</div>
  {investigation&&<div className="agentResult"><div className="agentResultHead"><span>AUTONOMOUS INVESTIGATOR</span><Badge t={investigation.agentic?'good':'watch'}>{investigation.agentic?'Tool-using AI':'Deterministic fallback'}</Badge></div>{agent?<><h3>{agent.summary}</h3><div className="agentColumns"><div><span>Business</span><p>{agent.business_assessment}</p><span>Technical</span><p>{agent.technical_assessment}</p></div><div><span>Infrastructure</span><p>{agent.infrastructure_assessment}</p><span>Leading hypothesis</span><p>{agent.leading_hypothesis} • {agent.confidence}%</p></div></div><div className="agentEvidence"><div><b>Evidence for</b>{(agent.evidence_for||[]).map((x,i)=><p key={i}>+ {x}</p>)}</div><div><b>Evidence against</b>{(agent.evidence_against||[]).map((x,i)=><p key={i}>− {x}</p>)}</div><div><b>Next actions</b>{(agent.next_actions||[]).map((x,i)=><p key={i}>→ {x}</p>)}</div></div></>:<><h3>{investigation.reason||investigation.deterministic_assessment?.assessment}</h3><p className="intelMuted">The deterministic intelligence engine is running now. Configure the OpenAI API key when you want the investigator to choose evidence tools and challenge hypotheses autonomously.</p></>}</div>}
 </section>
}

function JourneyPipeline({data,selected,onSelect}){
 const stages=data?.stages||[],mapping=data?.mapping||{};
 return <section className="panel"><div className="sectionHead"><div><span className="sectionIndex">01</span><div><h2>Business journey</h2><p>One booking journey, six stages. Selecting a stage filters the technical and infrastructure evidence to traces that touched that stage.</p></div></div><Badge t={data?.mode==='business-semantic'?'good':'watch'}>{data?.mode==='business-semantic'?'Semantic':'Route inferred'} • {data?.confidence||0}%</Badge></div>
  <div className="pipeline">{stages.map((s,idx)=><div className="stepWrap" key={s.name}><button className={`step ${selected===s.name?'active':''} ${!s.observed?'mutedStep':''}`} onClick={()=>onSelect(selected===s.name?'All':s.name)}><span>{String(idx+1).padStart(2,'0')}</span><b>{s.name}</b><strong>{s.count}</strong><small>mapped spans</small><div><em>p95 {ms(s.p95_ms)}</em><em>{pct(s.error_rate)} errors</em></div></button>{idx<stages.length-1&&<i className="connector">→</i>}</div>)}</div>
  <div className="mapping"><div><span>Mapping strategy</span><b>{mapping.strategy||'—'}</b></div><div><span>Mapped server spans</span><b>{mapping.mapped_server_spans||0}</b></div><div><span>Explicit semantic share</span><b>{pct(mapping.explicit_share_pct||0)}</b></div><p>{mapping.note}</p></div>
 </section>
}

function Sparkline({points,keyName,maxHint}){const vals=points.map(p=>Number(p[keyName])).filter(Number.isFinite),max=Math.max(maxHint||0,...vals,1),min=Math.min(...vals,0),range=Math.max(1,max-min);const xy=points.map((p,idx)=>{const v=Number(p[keyName]),x=points.length<=1?0:idx/(points.length-1)*100,y=Number.isFinite(v)?100-(v-min)/range*100:100;return `${x},${y}`}).join(' ');return <svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={xy}/></svg>}
function Correlation({data}){const c=data?.correlation||{},points=c.points||[],latest=points[points.length-1]||{},infra=data?.infra?.current;return <section className="panel"><div className="sectionHead"><div><span className="sectionIndex">02</span><div><h2>Application ↔ infrastructure correlation</h2><p>Same time buckets, same selected journey context. Use this to determine whether host behaviour moves with application latency.</p></div></div><Badge t={c.verdict?.startsWith('strong')?'bad':c.verdict?.startsWith('moderate')?'watch':'good'}>{c.verdict||'No relationship calculated'}</Badge></div><div className="correlationGrid"><div className="trendStack"><div className="trend"><div><span>Application p95</span><b>{ms(latest.p95_ms||0)}</b></div><Sparkline points={points} keyName="p95_ms"/></div><div className="trend"><div><span>Host CPU</span><b>{latest.cpu==null?'—':pct(latest.cpu)}</b></div><Sparkline points={points} keyName="cpu" maxHint={100}/></div><div className="trend"><div><span>Host memory</span><b>{latest.memory==null?'—':pct(latest.memory)}</b></div><Sparkline points={points} keyName="memory" maxHint={100}/></div><div className="timeAxis"><span>{when(points[0]?.time)}</span><span>{when(points[Math.floor(points.length/2)]?.time)}</span><span>{when(points[points.length-1]?.time)}</span></div></div><div className="corrSummary"><div><span>Latency ↔ CPU</span><b>{coeff(c.latency_cpu)}</b></div><div><span>Latency ↔ Memory</span><b>{coeff(c.latency_memory)}</b></div><div className="host"><span>Host</span><b>{infra?.hostname||'No sample'}</b><small>CPU {infra?pct(infra.cpu):'—'} • Memory {infra?pct(infra.memory):'—'} • Disk {infra?pct(infra.disk_max):'—'}</small></div><p>{c.note}</p></div></div></section>}

function Technical({data,traces,onTrace}){const edges=(data?.edges||[]).filter(e=>e.from!==e.to),stats=data?.service_stats||[];const sample=e=>(traces||[]).find(t=>(t.services||[]).includes(e.from)&&(t.services||[]).includes(e.to));return <section className="panel"><div className="sectionHead"><div><span className="sectionIndex">03</span><div><h2>Technical execution</h2><p>Services, dependencies and highest-risk operations for the currently selected business context.</p></div></div><Badge t={edges.length?'good':'watch'}>{edges.length?'Distributed context':'Single-service context'}</Badge></div><div className="technicalGrid"><div><div className="serviceCards">{stats.map((s,idx)=><article key={s.service}><div className="nodeName"><i className={`dot d${idx%4}`}/><div><b>{shortService(s.service)}</b><small>{s.service}</small></div></div><div className="nodeMetrics"><span>Traces <b>{s.traces}</b></span><span>p95 <b>{ms(s.p95_ms)}</b></span><span>Errors <b>{pct(s.error_rate)}</b></span></div></article>)}</div><div className="edges">{edges.map((e,idx)=>{const t=sample(e);return <button key={idx} disabled={!t} onClick={()=>t&&onTrace(t.trace_id)}><span>{shortService(e.from)}</span><b>→</b><span>{shortService(e.to)}</span><em>{e.calls} calls</em><small>p95 {ms(e.p95_ms)} • {pct(e.error_rate)} errors</small></button>})}</div></div><div className="riskList"><h3>Highest-risk operations</h3>{(data?.top_operations||[]).slice(0,8).map((o,idx)=><div className="risk" key={idx}><span>{String(idx+1).padStart(2,'0')}</span><div><b>{o.operation}</b><small>{o.service}</small></div><strong>{ms(o.p95_ms)}</strong><em>{pct(o.error_rate)}</em></div>)}</div></div></section>}
function TraceExplorer({traces,onTrace}){return <section className="panel"><div className="sectionHead"><div><span className="sectionIndex">04</span><div><h2>Trace explorer</h2><p>Open any trace to validate the executive conclusion against deterministic trace intelligence and the actual distributed waterfall.</p></div></div><Badge>{traces?.length||0} samples</Badge></div><div className="tableWrap"><table><thead><tr><th>Time</th><th>Stages</th><th>Entry operation</th><th>Service path</th><th>Duration</th><th>Spans</th><th>Status</th></tr></thead><tbody>{(traces||[]).map(t=><tr key={t.trace_id} onClick={()=>onTrace(t.trace_id)}><td>{when(t.start_time)}</td><td>{(t.journeys||[]).join(' → ')||'Unmapped'}</td><td><b>{t.root_operation||t.operations?.[0]||'unknown'}</b><small>{t.trace_id.slice(0,12)}…</small></td><td>{(t.services||[]).map(shortService).join(' → ')}</td><td>{ms(t.duration_ms)}</td><td>{t.span_count}</td><td><Badge t={t.error?'bad':t.distributed?'good':'neutral'}>{t.error?'Error':t.distributed?'Distributed':'Single'}</Badge></td></tr>)}</tbody></table></div></section>}
function Evidence({data}){return <section className="panel"><div className="sectionHead"><div><span className="sectionIndex">05</span><div><h2>Evidence & recommended next action</h2><p>Deterministic findings supporting the CEO summary.</p></div></div></div><div className="evidenceGrid"><div><h3>Observed</h3>{(data?.observations||[]).map((x,i)=><p key={i}>• {x}</p>)}</div><div><h3>Investigate next</h3>{(data?.actions||[]).map((x,i)=><p key={i}>→ {x}</p>)}</div></div></section>}

function TraceDrawer({trace,onClose}){
 if(!trace)return null;if(trace.loading)return <><div className="drawerBackdrop" onClick={onClose}/><aside className="drawer"><button onClick={onClose}>Close</button><p>Loading trace…</p></aside></>;if(trace.error)return <><div className="drawerBackdrop" onClick={onClose}/><aside className="drawer"><button onClick={onClose}>Close</button><p>{trace.error}</p></aside></>;
 const spans=trace.spans||[],ti=trace.intelligence||{},byId=new Map(spans.map(s=>[s.span_id,s])),depth=s=>{let d=0,p=s.parent_span_id,g=0;while(p&&byId.has(p)&&g++<12){d++;p=byId.get(p)?.parent_span_id}return Math.min(d,7)},min=spans.length?Math.min(...spans.map(s=>new Date(s.start_time).getTime())):0,ends=spans.map(s=>new Date(s.start_time).getTime()+Number(s.duration_ms||0)),max=ends.length?Math.max(...ends):min+1,range=Math.max(1,max-min),summary=trace.summary||{};
 return <><div className="drawerBackdrop" onClick={onClose}/><aside className="drawer"><div className="drawerHead"><div><span>TRACE INTELLIGENCE + WATERFALL</span><h2>{summary.root_operation||trace.trace_id}</h2><small>{trace.trace_id}</small></div><button onClick={onClose}>Close</button></div><div className="drawerKpis"><div><span>Total</span><b>{ms(summary.duration_ms||range)}</b></div><div><span>Spans</span><b>{summary.span_count||spans.length}</b></div><div><span>Services</span><b>{summary.service_count||0}</b></div><div><span>Errors</span><b>{summary.error_count||0}</b></div></div>{ti.dominant_contributor&&<div className="traceIntel"><div><span>Dominant exclusive execution</span><b>{ti.dominant_contributor.operation}</b><small>{shortService(ti.dominant_contributor.service)} • {ms(ti.dominant_contributor.self_time_ms)} self time • {pct(ti.dominant_contributor.execution_share_pct)} share</small></div><div><span>Critical path</span><b>{(ti.critical_path||[]).map(x=>shortService(x.service)).filter((x,i,a)=>i===0||x!==a[i-1]).join(' → ')||'—'}</b><small>{(ti.critical_path||[]).slice(0,5).map(x=>x.operation).join(' → ')}</small></div></div>}<div className="traceAttribution">{(ti.service_attribution||[]).slice(0,5).map(x=><div key={x.service}><span>{shortService(x.service)}</span><i><em style={{width:`${Math.min(100,x.execution_share_pct)}%`}}/></i><b>{pct(x.execution_share_pct)}</b></div>)}</div><div className="waterfall">{spans.map(s=>{const start=(new Date(s.start_time).getTime()-min)/range*100,width=Math.max(.7,Number(s.duration_ms||0)/range*100),parent=byId.get(s.parent_span_id),hop=parent&&parent.service!==s.service,error=Number(s.status_code)===2||Number(s.attrs?.['http.response.status_code']||0)>=500;return <div className={`wf ${hop?'hop':''}`} key={s.span_id}><div className="wfLabel" style={{paddingLeft:`${depth(s)*12}px`}}><b>{s.operation}</b><small>{shortService(s.service)} • {ms(s.duration_ms)}{hop?' • service hop':''}</small></div><div className="wfTrack"><i className={error?'err':''} style={{left:`${start}%`,width:`${Math.min(100-start,width)}%`}}/></div></div>})}</div></aside></>
}

export default function Dashboard(){
 const [range,setRange]=useState('15m'),[stage,setStage]=useState('All'),[d,setD]=useState(null),[err,setErr]=useState(''),[loading,setLoading]=useState(false),[trace,setTrace]=useState(null),[investigating,setInvestigating]=useState(false),[investigation,setInvestigation]=useState(null);
 async function load(){setLoading(true);try{const r=await fetch(`/api/overview?range=${encodeURIComponent(range)}&journey=Booking&stage=${encodeURIComponent(stage)}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'load failed');setD(j);setErr('');setInvestigation(null)}catch(e){setErr(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[range,stage]);
 async function openTrace(id){setTrace({loading:true,trace_id:id});try{const r=await fetch(`/api/trace?trace_id=${encodeURIComponent(id)}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'trace load failed');setTrace(j)}catch(e){setTrace({error:e.message,trace_id:id})}}
 async function investigate(){if(!d?.agent_id)return;setInvestigating(true);try{const r=await fetch('/api/investigate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({agent_id:d.agent_id,range,stage,mode:'quick'})}),j=await r.json();if(!r.ok)throw new Error(j.error||'investigation failed');setInvestigation(j)}catch(e){setInvestigation({reason:e.message,agentic:false})}finally{setInvestigating(false)}}
 return <main><Header data={d} range={range} setRange={setRange} stage={stage} setStage={setStage} onRefresh={load} loading={loading}/>{err&&<div className="errorBox">{err}</div>}<ExecutiveView data={d}/><IntelligencePanel data={d} onInvestigate={investigate} investigating={investigating} investigation={investigation}/><JourneyPipeline data={d?.journey} selected={stage} onSelect={setStage}/><Correlation data={d}/><Technical data={d?.technical} traces={d?.recent_traces} onTrace={openTrace}/><TraceExplorer traces={d?.recent_traces} onTrace={openTrace}/><Evidence data={d?.evidence}/><footer>SPARE-M • Observe → understand → hypothesize → verify → explain</footer><TraceDrawer trace={trace} onClose={()=>setTrace(null)}/></main>
}
